language: r
services: PostgreSQL

r_binary_packages:
  - ggplot2
  - RSQLite
  - RMySQL
  - knitr
  - Rcpp
r_github_packages:
  - jimhester/covr
  - hadley/lazyeval

before_install:
  - mkdir ~/.R

before_script:
# - psql -c 'create database lahman;' -U postgres
# - psql -c 'create database nycflights13;' -U postgres
# - psql -c 'create database test;' -U postgres
# Install dplyr package then cache sqlite and postgres version of Lahman
- R CMD INSTALL .
- Rscript -e "library(methods); library(dplyr); lahman_sqlite()"
- Rscript -e "library(methods); library(dplyr); nycflights13_sqlite()"
# lahman_postgres; #nycflights13_postgres()

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
env:
  - PKG_CXXFLAGS="-g -O3 -Wall -pedantic"

